# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  # Agent VM image name
  vmImageName: 'windows-latest'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: sdk
        version: '3.x'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'restore'
        projects: '$(System.DefaultWorkingDirectory)/*.sln'
        feedsToUse: 'select'

    - task: MSBuild@1
      inputs:
        solution: $(System.DefaultWorkingDirectory)/*.sln
        configuration: Release
        msbuildArguments: /p:DeployOnBuild=true

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: $(System.DefaultWorkingDirectory)/FuncatConfiguration/bin/Release/*.nupkg
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
        allowPackageConflicts: true

    - task: NuGetCommand@2
      inputs:
        command: 'push'
        packagesToPush: $(System.DefaultWorkingDirectory)/FuncatConfiguration.Abstractions/bin/Release/*.nupkg
        nuGetFeedType: 'external'
        publishFeedCredentials: 'nuget.org'
        allowPackageConflicts: true